name: MacOps
description: Mac/DevOps
meta_description: "this is a website"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://mrala.github.io'
google_analytics: 'UA-XXXXXXXX-X'

# Details for the RSS feed generator
url:            'http://mrala.github.io'
author:         'Ali'
